# Generated by Django 4.0.5 on 2022-06-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TierURL',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('main_url', models.URLField()),
                ('short_url', models.URLField(max_length=100, unique=True)),
            ],
        ),
    ]
