# Generated by Django 4.0.5 on 2022-06-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_alter_tierurl_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLVisit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visits', models.IntegerField()),
                ('tier_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urlvisits', to='urlshortner.tierurl')),
            ],
        ),
    ]
